- name: "kritisch"
  color: "d73a4a"
  description: "Kritische Probleme, die sofort behoben werden müssen"

- name: "hoch"
  color: "ff6b6b"
  description: "Hohe Priorität"

- name: "mittel"
  color: "ffa726"
  description: "Mittlere Priorität"

- name: "niedrig"
  color: "4fc3f7"
  description: "Niedrige Priorität"

# Issue Types
- name: "bug"
  color: "d73a4a"
  description: "Fehlerhafte Funktionalität"

- name: "feature"
  color: "a2eeef"
  description: "Neue Funktionalität oder Verbesserung"

- name: "dokumentation"
  color: "0075ca"
  description: "Verbesserung der Dokumentation"

- name: "aufgabe"
  color: "7057ff"
  description: "Allgemeine Aufgabe oder To-Do"

- name: "frage"
  color: "d876e3"
  description: "Frage oder Diskussion"

# Status Labels
- name: "in bearbeitung"
  color: "fbca04"
  description: "Wird gerade bearbeitet"

- name: "bereit für review"
  color: "0e8a16"
  description: "Bereit zur Überprüfung"

- name: "blockiert"
  color: "b60205"
  description: "Blockiert und kann nicht fortgesetzt werden"

- name: "wartet auf feedback"
  color: "f29513"
  description: "Wartet auf Rückmeldung"

# Schwierigkeit
- name: "einfach"
  color: "c5f015"
  description: "Einfach zu beheben, gut für Einsteiger"

- name: "mittel schwer"
  color: "fbca04"
  description: "Mittlerer Schwierigkeitsgrad"

- name: "schwer"
  color: "d93f0b"
  description: "Schwieriges Problem, erfordert Expertise"

# Kategorien
- name: "frontend"
  color: "1d76db"
  description: "Frontend-bezogene Änderungen"

- name: "backend"
  color: "0052cc"
  description: "Backend-bezogene Änderungen"

- name: "api"
  color: "006b75"
  description: "API-bezogene Änderungen"

- name: "datenbank"
  color: "5319e7"
  description: "Datenbank-bezogene Änderungen"
