sources:
  npm:
    enabled: true
    dependencies_file: package-lock.json

apps:
  - name: alertmanager-gotify
    path: .
    cache_path: .licenses/cache
    sources:
      - npm
    allow:
      licenses:
        - mit
        - apache-2.0
        - bsd-2-clause
        - bsd-3-clause
        - isc
    ignore:
      licenses:
        - unknown
        - other
