name: alertmanager-gotify
cache_path: .licenses/cache

apps:
  - name: alertmanager-gotify
    path: .
    sources:
      - npm
    allow:
      licenses:
        - mit
        - apache-2.0
        - bsd-2-clause
        - bsd-3-clause
        - isc
    ignore:
      licenses:
        - unknown
        - other
