name: Docker Linting

on:
  push:
    paths:
      - '.github/Dockerfile'
      - '*.yml'
  pull_request:
    paths:
      - '.github/Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: .github/Dockerfile
          failure-threshold: warning

      - name: Check Docker Compose
        uses: docker/compose-cli-action@v3
        with:
          command: config
