name: Pull Request Labeler

on:
 pull_request:
  types: [opened, synchronize, reopened]

permissions:
 contents: read
 pull-requests: write

jobs:
 label:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: kentaro-m/auto-label@main
     with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      config-path: .github/labeler.yml
