name: Code Linting

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '*.json'
      - '*.md'
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"

      - name: Lint package.json
        uses: cytopia/action-npm-lint@v1
