name: Renovate Dependency Updates

on:
 schedule:
  - cron: "0 3 * * *"

permissions:
 contents: write
 pull-requests: write
 checks: write

jobs:
 renovate:
  runs-on: ubuntu-latest
  steps:
   - name: Run Renovate
     uses: renovatebot/github-action@v19
     with:
      configurationFile: renovate.json
